#!/usr/bin/env racket
#lang racket
(require srfi/13
         "lib/liveness.rkt"
         "lib/parse.rkt"
         "lib/types.rkt")

(define (main)
  (let ([filename (command-line #:args (filename) filename)])
    (let ([text (call-with-input-file filename read)])
      (display (liveness (parseFun text #t))))))

(main)

